### ISSUE TITLE
Can a trained model be provided on GitHub for testing?

### ISSUE THREAD

**Issue by 605521553** [NOrangeeroli/SecondPose#5]

**Comment by hiyyg** [comment]
+1

**Comment by NOrangeeroli** [comment]
Hi we've provided the checkpoint.

**Comment by hiyyg** [comment]
Thank you for providing the checkpoint.

From the checkpoints, we can know that the PN2 ckpt is actually from VI-Net (they have the same checksum). For the rotation ckpt, the epoch number is 38. Does this mean the ckpt with an intermediate epoch number instead of the final ckpt is used to report the results?

Besides, the provided dataset code and the checkpoints are only for NOCS-REAL. Could you also kindly provide the dataset code and the checkpoints for HouseCat6D?
