### ISSUE TITLE
[Confirmed by the author] Rotation loss in the code is different from that in paper

### ISSUE THREAD

**Issue by hiyyg** [NOrangeeroli/SecondPose#9]
Hi @NOrangeeroli,

In the paper, you said that you were only using the L1 loss for the 9d rotation matrix. However, in the code, you are still using the VI-Net rotation loss. Could you kindly explain this?

**Comment by NOrangeeroli** [comment]
Hi,
Thanks for the question. The VI-net paper uses a special classify-then-regress process, which is closely related to it's core design, and is not the focus of our paper. for the regress loss, it uses L1 loss. To avoid verbose explanations, we didn't focus on these details and just wrote L1 loss, since our method can also be used with regression-only VI-Net.

Best,
Yamei

**Comment by hiyyg** [comment]
Thanks for the clarification. So based on what you said, the description in the paper is incorrect. You did not show any results for regression only. The losses are actually exactly the same as those in VI-Net.
